---
- hosts: exemplo
  remote_user: root
  tasks:
  - name: "Install Git"
    apt: name=update state=latest
 
  - name: Add the key used to Nginx pkg
    apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
 
  - name: Update packages and install Nginx
    apt: name=nginx update_cache=yes
